import SocialNav from '@/components/socialNav'
import { Inter } from 'next/font/google'
import styles from '@/styles/socialHome.module.css'
import SidebarSocial from '@/components/sidebarSocial'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SocialLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocialNav />
        <main className={styles.main}>
          <div className={styles.sidebar}>
            <SidebarSocial />
          </div>
          {children}
        </main>


      </body>
    </html>
  )
}
